### ISSUE TITLE
Driver search location

### ISSUE THREAD

**Issue by RuralBrick** [RuralBrick/hagglehaul#16]
## User Story
As a **driver**, I would like **to search trips by location** so that **I can find trips I want to bid on**.

## Detailed Description
I would like to only drive and work trips in certain areas. To save time when I'm looking for trips, the trip discovery page should only show me locations I'd like to serve.

## Acceptance Criteria
- [ ] Given **i open the page with a list of trips**, then **i see a way to filter by location (e.g., city/zip)**
- [ ] Given **select a location to filter by**, the **i only see trips with origin or destination within the location**

**Comment by jaczhi** [comment]
Per scrum, moving to sprint 4
