### ISSUE TITLE
Driver autobid bids

### ISSUE THREAD

**Issue by RuralBrick** [RuralBrick/hagglehaul#27]
## User Story
As a **driver**, I would like **to autobid by the current lowest bid** so that **I can tailor my autobidder preferences**.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**

**Comment by jaczhi** [comment]
Duplicate with #40
