### ISSUE TITLE
Rider trip page

### ISSUE THREAD

**Issue by RuralBrick** [RuralBrick/hagglehaul#28]
## User Story
As a **rider**, I would like **to see all trips I have posted** so that **I can keep track of them**.

## Detailed Description
(This page may also be called a *dashboard*). I want to be able to view trips in various states and manage them, dependent on the state the trip is on. 

## Acceptance Criteria
- [ ] Given **trip newly posted**, then **trip shows up somwhere on dashboard**
- [ ] Given **trip newly posted**, then **trip properly shows up under trips in bidding**
- [ ] Given **trip newly posted**, then **details that dashboard shows are accurate**
- [ ] Given **trip updated**, then **details on dashboard reflect changes**
- [ ] Given **bid bought**, then **trip that bid was on moves from in bidding to confirmed**
- [ ] Given **trip moved between listings**, then **relevant details remain the same**
- [ ] Given **trip listing clicked**, then **trip info page loads**

**Comment by jaczhi** [comment]
Per scrum, moving to sprint 4
