### ISSUE TITLE
Users should be able to create and log in to their accounts.

### ISSUE THREAD

**Issue by RuralBrick** [RuralBrick/hagglehaul#45]
## Epic
Riders, drivers, and potentially companies should be able to create accounts. These accounts will then be used to access and interact with the rest of the system, as well as house personal and contact information. Users should also be able to edit their public information. This includes contact details, which should be exchanged between riders and drivers once a trip has been finalized.

## User Stories
- [x] story #1
- [x] story #2
- [x] story #3
- [x] story #4
- [x] story #5
- [x] story #6
- [ ] story #7
- [ ] story #8

**Comment by jaczhi** [comment]
Note to TA: non-complete stories in this epic are not part of our minimum viable product
