### ISSUE TITLE
Drivers should be able to bid on trips.

### ISSUE THREAD

**Issue by RuralBrick** [RuralBrick/hagglehaul#47]
## Epic
Drivers should be able to look up trips they want to bid on based on their preferences. After finding such trips, they should then be able to place an initial bid on it. Potential quality-of-life features to add later include being able to see the pre-calculated routes of trips with traffic information and an autobidder.

## User Stories
- [x] story #51 
- [x] story #52 
- [ ] story #15
- [x] story #16
- [x] story #19
- [x] story #20
- [x] story #21
- [ ] story #22
- [ ] story #23
- [ ] story #24
- [ ] story #25
- [ ] story #26
- [x] story #27
- [ ] story #17
- [ ] story #18

**Comment by jaczhi** [comment]
Closing as complete for purposes of project tracking - MVP complete
