### ISSUE TITLE
Riders should be able to manage their trips.

### ISSUE THREAD

**Issue by RuralBrick** [RuralBrick/hagglehaul#48]
## Epic
Riders should be able to see and modify all of the trips they have posted on a unified dashboard. They should also be able to engage with the drivers that have bid on these trips, including buying their bid and finalizing a trip. After which, riders should be able to take their trip with their driver and rate them afterwards.

## User Stories
- [x] story #28
- [ ] story #29
- [x] story #30
- [x] story #31
- [x] story #32
- [ ] story #33
- [x] story #34
- [x] story #35
- [x] story #36

**Comment by jaczhi** [comment]
Closing as complete for purposes of project tracking - MVP complete
