### ISSUE TITLE
Drivers should be able to manage the trips they have bid on.

### ISSUE THREAD

**Issue by RuralBrick** [RuralBrick/hagglehaul#50]
## Epic
Drivers should be able to keep tabs on the trips they have put an initial bid on. They should be able to see other drivers' bids be notified if their bid is bought. From there, they should be able to take their rider on their trip and rate them afterwards.

## User Stories
- [x] story #49
- [x] story #38
- [x] story #39
- [x] story #42
- [x] story #43
- [x] story #44
- [ ] story #37
- [ ] story #40
- [ ] story #41

**Comment by jaczhi** [comment]
Closing as complete for purposes of project tracking - MVP complete
