### ISSUE TITLE
Driver see trip thumbnail

### ISSUE THREAD

**Issue by RuralBrick** [RuralBrick/hagglehaul#52]
## User Story
As a **driver**, I would like **to see trip map thumbnails** so that **I can better choose trips to bid on**.

## Detailed Description
I would like to see a compact map that shows the full route, rough landmarks, and other helpful details about each trip, so that I can quickly judge whether this is a feasible/reasonable trip for me to bid on.

## Acceptance Criteria
- [ ] Given **thumbnail**, then **minimap + route**
- [ ] Given **trip search page**, then **trip listings have thumbnails**
- [ ] Given **trip info page**, then **thumbnail exists somewhere**
- [ ] Given **confirmed trips listing**, then **thumbnail**
- [ ] Given **my bid listing**, then **trip thumbnail**

**Comment by jaczhi** [comment]
Review completed; closed by currently merged branches
