### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by jaczhi** [RuralBrick/hagglehaul#55]
## Description

Please complete UI design and mockups. 

https://docs.google.com/presentation/d/1gI9p9n1U5_6ViWmmXusdZAwcCQPebQGsiNtmUfRWJnU/edit#slide=id.p

**Comment by jardondaful** [comment]
The UI mockups have been completed in Figma by Jordan Lin and Richard Zhu. Here are the links to their mockups

Jordan LIn: https://www.figma.com/file/aRsCdcrwyl5hrJN927dUm2/HaggleHaul?type=design&node-id=0%3A1&mode=design&t=fyaJQ4Dk8zLANXTl-1

Richard Zhu: https://www.figma.com/file/JSYqQFERJzH9GNKawvM5Rf/Untitled?type=design&node-id=0%3A1&mode=design&t=PiXeEntc5SirB2qJ-1
